### ISSUE TITLE
Decide package name of this project.

### ISSUE THREAD

**Issue by jkawamoto** [TrishGillett/pysdpt3glue#15]
PySDPT3glue is one candidate but little bit longer and contains capital letters.

**Comment by TrishGillett** [comment]
After discussion, we've agreed to call it it sdpt3glue for purposes of PyPI (since the py is implied) and leave the name unchanged here for now.

**Comment by jkawamoto** [comment]
Also, need to pick classifiers from https://pypi.python.org/pypi?%3Aaction=list_classifiers

**Comment by TrishGillett** [comment]
Maybe:
Intended Audience :: Science/Research
Topic :: Scientific/Engineering :: Mathematics

**Comment by jkawamoto** [comment]
👍

**Comment by jkawamoto** [comment]
Commit 0dd2c85 sets the classifiers.
