### ISSUE TITLE
Confirm how cvxpy returns cvxopt version

### ISSUE THREAD

**Issue by TrishGillett** [TrishGillett/pysdpt3glue#7]
Which is it:
1. The cvxopt data is not particularly symmetrized
2. The cvxopt data has been symmetrized
3. The cvxopt solver only actually reads the upper triangle and just assumes the lower triangle will hold the same values, so is it possible that cvxopt returns the data with the lower triangle zeroed out so that we need to fill it in manually? (Obviously, this possibility would be the most dangerous!)

TO DO:
- [x] Write a test that starts with a known asymmetric problem and tests if it ends up symmetric **and with the correct coefficients**

**Comment by TrishGillett** [comment]
When writing something like X = cvxpy.Semidef(3), this will not be an issue because the upper and lower triangles are not created using different variables.  Maybe this is an issue for more complicated SDP constraints though.

**Comment by SteveDiamond** [comment]
The cvxopt solver only reads the upper triangle (or lower triangle, I forget) and assumes the lower (upper) triangle holds the same values. It won't change the data though.

**Comment by TrishGillett** [comment]
Hi Steve, when you say it won't change the data do you mean that the `'A'`, `'G'`, `'c'` elements of `problem_dict = Problem.get_problem_data('CVXOPT')` will always have the coefficients for PSD matrices filled in symmetrically?

**Comment by SteveDiamond** [comment]
CVXPY ensures they're filled in symmetrically, but I meant that even if
they weren't filled in symmetrically CVXOPT wouldn't alter the matrices
themselves. It would just produce a solution based on only reading the
upper triangle of the coefficients for the PSD matrices.

**Comment by TrishGillett** [comment]
Yes, I understand about the CVXOPT solver.  In this case I'm grabbing the CVXOPT format data but then doing my own thing with it, not sending it to the CVXOPT solver, so I needed to rule out the possibility that CVXPY's get_problem_data('CVXOPT') might take a shortcut and only fill in one triangle based on an assumption that the data is just going to get used in CVXOPT anyway.  With that settled, I can close this issue up now.  Thanks for your help!
